INSERT INTO HOSPITAL (HOSPITAL_ID, NAME) VALUES('4', 'Rockcliffe');
INSERT INTO CAMPUS (CAMPUS_ID, ADDRESS) VALUES('4', '275 Estelle');
INSERT INTO STAFF (STAFF_ID, PROFESSION, NAME, PHONE_NUMBER) VALUES('1024', 'Radiologist', 'Diane Kruger', '416-449-8878');
INSERT INTO EPISODE_OF_CARE (ENCOUNTER_ID, DIAGNOSIS, ADMIT_DATE) VALUES('567582', 'Fractured Wrist','26-JAN-19');